/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libproject.librarypro;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.io.*;
import java.util.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author niamh
 */
//This program brings values from a txt file that can be edited to add to and/or can show that data. 
//There are two differnt sets of data , a person and a book, these are then used to identify what person is associated with what ID number. 
//The ID numbers are used to lend books out to people, the program has the abilty to only have one book lent out at a time
public class LibraryProGui extends javax.swing.JPanel {
    private static HashMap<Integer, Integer> bookMap = new HashMap<Integer, Integer>();
    private static HashMap<Integer, ArrayList<Integer>> personMap = new HashMap<Integer, ArrayList<Integer>>();
    private static ArrayList<Person> fileDataPerson = new ArrayList<Person>();
    private static ArrayList<Book> fileDataBook = new ArrayList<Book>();
    private static ArrayList<Integer> personBookIDs = new ArrayList<Integer>();
    
    /**
     * Creates new form LibraryProGui
     */
    public LibraryProGui() {
        initComponents();
        
        String fileNamePerson = "person.txt";
        readFilePerson(fileNamePerson, fileDataPerson);
        
        String fileNameBook = "book.txt"; 
        readFileBook(fileNameBook, fileDataBook);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        ShowPnAndBk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ShowPersonButton = new javax.swing.JButton();
        ShowBookButton = new javax.swing.JButton();
        AddBook = new javax.swing.JPanel();
        BookNeTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AuthorNeTxt = new javax.swing.JTextField();
        BookISBNTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BookIDNumTxt = new javax.swing.JTextField();
        AddBookBtn = new javax.swing.JButton();
        AddPerson = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PersonLtNeTxt = new javax.swing.JTextField();
        PersonFtNeTxt = new javax.swing.JTextField();
        AddPersonBtn = new javax.swing.JButton();
        PersonIDNumTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Lending = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LendPersonIDNumTxt = new javax.swing.JTextField();
        LendBookIDNumTxt = new javax.swing.JTextField();
        LendBtn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(450, 450));

        jLabel8.setText("Show Person Information");

        jLabel9.setText("Show Book Information");

        ShowPersonButton.setText("Press");
        ShowPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPersonButtonActionPerformed(evt);
            }
        });

        ShowBookButton.setText("Press");
        ShowBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowPnAndBkLayout = new javax.swing.GroupLayout(ShowPnAndBk);
        ShowPnAndBk.setLayout(ShowPnAndBkLayout);
        ShowPnAndBkLayout.setHorizontalGroup(
            ShowPnAndBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPnAndBkLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ShowPnAndBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(52, 52, 52)
                .addGroup(ShowPnAndBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowBookButton)
                    .addComponent(ShowPersonButton))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        ShowPnAndBkLayout.setVerticalGroup(
            ShowPnAndBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPnAndBkLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ShowPnAndBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowPersonButton)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(ShowPnAndBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ShowBookButton))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Show Person and Book", ShowPnAndBk);

        BookNeTxt.setText("Enter Name");

        jLabel1.setText("What is the book name:");

        jLabel2.setText("What is the authors name:");

        jLabel3.setText("What is the books ISBN:");

        AuthorNeTxt.setText("Enter Name");

        BookISBNTxt.setText("Enter ISBN");
        BookISBNTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookISBNTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("What is the books id number:");

        BookIDNumTxt.setText("Enter ID");

        AddBookBtn.setText("Add Book");
        AddBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddBookLayout = new javax.swing.GroupLayout(AddBook);
        AddBook.setLayout(AddBookLayout);
        AddBookLayout.setHorizontalGroup(
            AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddBookLayout.createSequentialGroup()
                        .addGap(32, 143, Short.MAX_VALUE)
                        .addComponent(AddBookBtn)
                        .addGap(52, 52, 52))
                    .addGroup(AddBookLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookISBNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        AddBookLayout.setVerticalGroup(
            AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BookNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(AuthorNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookISBNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(AddBookBtn)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Add Book", AddBook);

        jLabel5.setText("What is the persons first name:");

        jLabel6.setText("What is the persons last name:");

        PersonLtNeTxt.setText("Enter Name");

        PersonFtNeTxt.setText("Enter Name");

        AddPersonBtn.setText("Add Person");
        AddPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPersonBtnActionPerformed(evt);
            }
        });

        PersonIDNumTxt.setText("Enter ID");

        jLabel7.setText("What is the persons id number:");

        javax.swing.GroupLayout AddPersonLayout = new javax.swing.GroupLayout(AddPerson);
        AddPerson.setLayout(AddPersonLayout);
        AddPersonLayout.setHorizontalGroup(
            AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPersonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonLtNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonFtNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddPersonBtn)
                .addGap(66, 66, 66))
        );
        AddPersonLayout.setVerticalGroup(
            AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPersonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPersonLayout.createSequentialGroup()
                        .addComponent(PersonFtNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PersonLtNeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PersonIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addComponent(AddPersonBtn)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Person", AddPerson);

        jLabel11.setText("What is the persons id number:");

        jLabel12.setText("What is the books id number:");

        LendPersonIDNumTxt.setText("Enter ID");

        LendBookIDNumTxt.setText("Enter ID");

        LendBtn.setText("Lend");
        LendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LendingLayout = new javax.swing.GroupLayout(Lending);
        Lending.setLayout(LendingLayout);
        LendingLayout.setHorizontalGroup(
            LendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LendingLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(LendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LendingLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(LendPersonIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LendingLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LendBookIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LendingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LendBtn)
                .addGap(81, 81, 81))
        );
        LendingLayout.setVerticalGroup(
            LendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LendingLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(LendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LendPersonIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(LendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LendBookIDNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addComponent(LendBtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lending", Lending);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPersonButtonActionPerformed
        // TODO add your handling code here:
        showListPerson(fileDataPerson);
    }//GEN-LAST:event_ShowPersonButtonActionPerformed

    private void ShowBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBookButtonActionPerformed
        // TODO add your handling code here:
        showListBook(fileDataBook);
    }//GEN-LAST:event_ShowBookButtonActionPerformed
//Takes data from the text fields and when the add book button is pressed it runs the add book method
    private void AddBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookBtnActionPerformed
        // TODO add your handling code here:
        String authorName = AuthorNeTxt.getText();
        String bookName = BookNeTxt.getText();
        String ISBN = BookISBNTxt.getText();
        int bookIDnum = Integer.parseInt(BookIDNumTxt.getText());
        try {
            addBook(authorName, bookName, ISBN, bookIDnum);
        } catch (IOException ex) {
            Logger.getLogger(LibraryProGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddBookBtnActionPerformed
//Takes data from the text fields and when the add person button is pressed it runs the add person method
    private void AddPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPersonBtnActionPerformed
        // TODO add your handling code here:
        String firstName = PersonFtNeTxt.getText();
        String lastName = PersonLtNeTxt.getText();
        int personIDnum = Integer.parseInt(PersonIDNumTxt.getText());
        try {
            addPerson(firstName,lastName,personIDnum);
        } catch (IOException ex) {
            Logger.getLogger(LibraryProGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddPersonBtnActionPerformed
//Takes the data entered in the text fields in the lending tab and runs the lending method with the data
    private void LendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LendBtnActionPerformed
        // TODO add your handling code here:
        int lendBookIDNum = Integer.parseInt(LendBookIDNumTxt.getText());
        int lendPersonIDNum = Integer.parseInt(LendPersonIDNumTxt.getText());
        personBookIDs.add(lendBookIDNum);
        lending(lendBookIDNum, lendPersonIDNum);
    }//GEN-LAST:event_LendBtnActionPerformed

    private void BookISBNTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookISBNTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookISBNTxtActionPerformed
//Takes the array list and person txt file and reads the data and puts it in the array
    public static void readFilePerson (String fileNamePerson, ArrayList<Person> fileDataPerson){
        File file = new File(fileNamePerson);
        try{
            Scanner fileScan = new Scanner(file);
            while(fileScan.hasNextLine()){
                String[] eachItem = fileScan.nextLine().split(",");
                try{
                    int idNum = Integer.parseInt(eachItem[2].trim());
                    fileDataPerson.add(new Person(eachItem[0], eachItem[1], idNum));
                }
                catch(NumberFormatException e){
                    System.out.println(" ignoring this line - couldn't parse ");
                }
            }
        }
        catch(FileNotFoundException e){
            System.out.println(" File not found ");
            System.exit(1);
        }
    }
//Takes the data from the person text files, reads that data and adds it into an arraylist so that the data can be used
    public static void readFileBook (String fileNameBook, ArrayList<Book> fileDataBook){
        File file = new File(fileNameBook);
        try{
            Scanner fileScan = new Scanner(file);
            while(fileScan.hasNextLine()){
                String[] eachItem = fileScan.nextLine().split(",");
                try{
                    int idBookNum = Integer.parseInt(eachItem[3].trim());
                    fileDataBook.add(new Book(eachItem[0], eachItem[1], eachItem[2], idBookNum));
                }
                catch(NumberFormatException e){
                    System.out.println(" ignoring this line - couldn't parse ");
                }
            }
        }
        catch(FileNotFoundException e){
            System.out.println(" File not found ");
            System.exit(1);
        }
    }
//prints out the details of the person txt file from the array list
    public static void showListPerson(ArrayList<Person> fileDataPerson){
        System.out.println("LIST of details");
       for(Person person:fileDataPerson){
           System.out.print(person.getPersonIDnum()+": ");
           System.out.print(person.getFirstName()+" ");
           System.out.println(person.getLastName());
        }
    }
 //Takes the data in the book data arraylist and prints out the infomation
    public static void showListBook(ArrayList<Book> fileDataBook){
        System.out.println("LIST of details");
       for(Book book:fileDataBook){
           System.out.println(book.getBookName());
           System.out.println(book.getAuthorName());
           System.out.println(book.getISBN());
           System.out.println(book.getBookIDnum());
        }
    }
//When the add book button is pressed it runs this method that takes the data from the book text fields and prints thme into the book text field in the right order
    public static void addBook(String authorName, String bookName, String ISBN, int bookIDnum) throws IOException{
        FileWriter fw = null;
        BufferedWriter bw = null;
        PrintWriter pw = null;
        
        try{
            fw = new FileWriter("book.txt", true);
            bw = new BufferedWriter(fw);
            pw = new PrintWriter(bw);
            pw.print(bookName+ ",");
            pw.print(authorName+",");
            pw.print(ISBN+",");
            pw.println(bookIDnum);
            System.out.println("Book Data Successfully appended into file");
            pw.flush();
        }
        finally{
            try{
                pw.close();
                bw.close();
                fw.close();
            } catch(IOException io){}
        }
    }
//When the add person button is pressed it runs this method that takes the data from the person text fields and prints them out into the person text file in the correct order
    public static void addPerson(String firstName, String lastName, int personIDnum) throws IOException{
        FileWriter fw = null;
        BufferedWriter bw = null;
        PrintWriter pw = null;
        
        try{
            fw = new FileWriter("person.txt", true);
            bw = new BufferedWriter(fw);
            pw = new PrintWriter(bw);
            pw.print(firstName + ",");
            pw.print(lastName +",");
           pw.println(personIDnum);
            System.out.println("Person Data Successfully appended into file");
            pw.flush();
        }
        finally{
            try{
                pw.close();
                bw.close();
                fw.close();
            } catch(IOException io){}
        }
    }
    public static void lending(int lendBookIDNum, int lendPersonIDNum){
        //bookMap.remove(lendBookIDNum);
        personMap.remove(lendBookIDNum);
        bookMap.put(lendBookIDNum,lendPersonIDNum);
        personMap.put(lendPersonIDNum, personBookIDs);
        System.out.println("Book Map " + bookMap);
        System.out.println("Person Map " + personMap);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBook;
    private javax.swing.JButton AddBookBtn;
    private javax.swing.JPanel AddPerson;
    private javax.swing.JButton AddPersonBtn;
    private javax.swing.JTextField AuthorNeTxt;
    private javax.swing.JTextField BookIDNumTxt;
    private javax.swing.JTextField BookISBNTxt;
    private javax.swing.JTextField BookNeTxt;
    private javax.swing.JTextField LendBookIDNumTxt;
    private javax.swing.JButton LendBtn;
    private javax.swing.JTextField LendPersonIDNumTxt;
    private javax.swing.JPanel Lending;
    private javax.swing.JTextField PersonFtNeTxt;
    private javax.swing.JTextField PersonIDNumTxt;
    private javax.swing.JTextField PersonLtNeTxt;
    private javax.swing.JButton ShowBookButton;
    private javax.swing.JButton ShowPersonButton;
    private javax.swing.JPanel ShowPnAndBk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
